apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: webapp
type: Opaque
stringData:
  access-key: test
  secret-access-key: test
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: localstack-secretsmanager
  namespace: webapp
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      role: arn:aws:iam::000000000000:role/eso-role
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: access-key
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret-access-key
