apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webapp-secrets
  namespace: webapp
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: localstack-secretsmanager
    kind: SecretStore
  target:
    name: webapp-secret          # name of the K8s Secret ESO will create/manage
    creationPolicy: Owner
  data:
    - secretKey: db_password
      remoteRef:
        key: webapp/secrets
        property: db_password
    - secretKey: api_key
      remoteRef:
        key: webapp/secrets
        property: api_key
    - secretKey: secret_key
      remoteRef:
        key: webapp/secrets
        property: secret_key
