apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: webapp-db-secrets
  namespace: webapp
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: localstack-secretsmanager
    kind: SecretStore
  target:
    name: webapp-db-secret
    creationPolicy: Owner
  data:
    - secretKey: db_url
      remoteRef:
        key: webapp/db-credentials
        property: db_url
    - secretKey: db_host
      remoteRef:
        key: webapp/db-credentials
        property: db_host
    - secretKey: db_password
      remoteRef:
        key: webapp/db-credentials
        property: db_password
