apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.eso.aws.accessKey | quote }}
  secret-access-key: {{ .Values.eso.aws.secretAccessKey | quote }}
