apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "webapp.name" . }}-db-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.eso.refreshInterval }}
  secretStoreRef:
    name: localstack-secretsmanager
    kind: SecretStore
  target:
    name: {{ include "webapp.name" . }}-db-secret
    creationPolicy: Owner
  data:
    - secretKey: db_url
      remoteRef:
        key: {{ .Values.eso.secrets.dbSecret }}
        property: db_url
    - secretKey: db_host
      remoteRef:
        key: {{ .Values.eso.secrets.dbSecret }}
        property: db_host
    - secretKey: db_password
      remoteRef:
        key: {{ .Values.eso.secrets.dbSecret }}
        property: db_password
