apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: localstack-secretsmanager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.eso.region }}
      role: {{ .Values.eso.roleArn }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: access-key
          secretAccessKeySecretRef:
            name: aws-credentials
            key: secret-access-key
