apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "webapp.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.eso.refreshInterval }}
  secretStoreRef:
    name: localstack-secretsmanager
    kind: SecretStore
  target:
    name: {{ include "webapp.name" . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: db_password
      remoteRef:
        key: {{ .Values.eso.secrets.appSecret }}
        property: db_password
    - secretKey: api_key
      remoteRef:
        key: {{ .Values.eso.secrets.appSecret }}
        property: api_key
    - secretKey: secret_key
      remoteRef:
        key: {{ .Values.eso.secrets.appSecret }}
        property: secret_key
